transaction = {
  "en": {
    -9: "Validation error: Merchant code not entered in settings - Return address not entered - Description exceeds the allowed limit - Payment amount is less than or exceeds the allowed limit.",
    -10: "The IP or Merchant code is incorrect.",
    -11: "The Merchant code is not active, please contact Zarinpal customer support.",
    -12: "Too many attempts in a short period, please notify Zarinpal customer support.",
    -15: "The payment gateway has been suspended, please contact Zarinpal customer support.",
    -16: "The merchant's approval level is below Silver.",
    -17: "Merchant is limited at the Blue level.",
    100: "Operation successful.",
    -30: "The merchant does not have access to the floating shared settlement service.",
    -31: "Add a bank account for settlement in the panel. The entered amounts for sharing are incorrect.",
    -32: "The entered amount exceeds the total transaction amount.",
    -33: "The entered percentages are incorrect.",
    -34: "The entered amount exceeds the total transaction amount.",
    -35: "The number of recipients for sharing exceeds the allowed limit.",
    -36: "The minimum amount for sharing must be 10,000 Rials.",
    -37: "One or more IBAN numbers entered for sharing are deactivated by the bank.",
    -38: "Error: Incorrect IBAN definition, please try again in a few minutes.",
    -39: "An error occurred, please notify Zarinpal customer support.",
    -40: "Error in additional parameters. The 'expire_in' parameter is invalid.",
    -41: "The maximum payment amount is 100 million Tomans.",
    -50: "The paid amount differs from the amount sent in the verify method.",
    -51: "Payment unsuccessful.",
    -52: "An unexpected error occurred. Please contact Zarinpal customer support.",
    -53: "The payment does not belong to this merchant code.",
    -54: "Invalid authority.",
    -55: "The specified transaction was not found.",
    -60: "It is not possible to reverse the transaction with the bank.",
    -61: "The transaction was not successful or has already been reversed.",
    -62: "The gateway IP has not been set.",
    -63: "The maximum time (30 minutes) for reversing this transaction has expired.",
    101: "The transaction has been verified.",
    400: "The payment has not been approved by the payment gateway",
    403: "The transaction has been verified.",
    404: "Verification was unsuccessful.",
    405: "An error occurred during validation, the payment information has been sent to the admins, and the result will be announced to you in the bot.",
    "operation_failed_user": 'An error occurred while executing the operation! The amount of {0} Tomans has been added to your wallet. Please perform the desired operation through the credit of the wallet.',
    "successful_pay": 'Your payment has been successfully confirmed! Transaction number: {0}',
    "payment_failed_title": "Failed payment",
     "payment_failed": "Your payment failed",
     "payment_failed_body": "Unfortunately, your payment has failed. Error reason:",
     "error_code_lable": "Error Code",
     "extra_text": "If you think there is a problem, please contact support through the bot.",
     "back_to_bot": "Back to bot",
  },
  "fa": {
    -9: "خطای اعتبار سنجی: مرچنت کد داخل تنظیمات وارد نشده باشد - آدرس بازگشت وارد نشده باشد - توضیحات بیش از حد مجاز - مبلغ پرداختی کمتر یا بیشتر از حد مجاز است",
    -10: "ای پی یا مرچنت كد پذیرنده صحیح نیست.",
    -11: "مرچنت کد فعال نیست، پذیرنده مشکل خود را به امور مشتریان زرین‌پال ارجاع دهد.",
    -12: "تلاش بیش از دفعات مجاز در یک بازه زمانی کوتاه به امور مشتریان زرین پال اطلاع دهید",
    -15: "درگاه پرداخت به حالت تعلیق در آمده است، پذیرنده مشکل خود را به امور مشتریان زرین‌پال ارجاع دهد.",
    -16: "سطح تایید پذیرنده پایین تر از سطح نقره ای است.",
    -17: "محدودیت پذیرنده در سطح آبی",
    100: "عملیات موفق",
    -30: "پذیرنده اجازه دسترسی به سرویس تسویه اشتراکی شناور را ندارد.",
    -31: "حساب بانکی تسویه را به پنل اضافه کنید. مقادیر وارد شده برای تسهیم درست نیست.",
    -32: "مبلغ وارد شده از مبلغ کل تراکنش بیشتر است.",
    -33: "درصدهای وارد شده صحیح نیست.",
    -34: "مبلغ وارد شده از مبلغ کل تراکنش بیشتر است.",
    -35: "تعداد افراد دریافت کننده تسهیم بیش از حد مجاز است.",
    -36: "حداقل مبلغ جهت تسهیم باید ۱۰۰۰۰ ریال باشد.",
    -37: "یک یا چند شماره شبای وارد شده برای تسهیم از سمت بانک غیر فعال است.",
    -38: "خطا٬عدم تعریف صحیح شبا٬لطفا دقایقی دیگر تلاش کنید.",
    -39: "خطایی رخ داده است به امور مشتریان زرین پال اطلاع دهید.",
    -40: "خطا در پارامترهای اضافی. پارامتر expire_in معتبر نیست.",
    -41: "حداکثر مبلغ پرداختی ۱۰۰ میلیون تومان است.",
    -50: "مبلغ پرداخت شده با مقدار مبلغ ارسالی در متد وریفای متفاوت است.",
    -51: "پرداخت ناموفق.",
    -52: "خطای غیر منتظره‌ای رخ داده است. پذیرنده مشکل خود را به امور مشتریان زرین‌پال ارجاع دهد.",
    -53: "پرداخت متعلق به این مرچنت کد نیست.",
    -54: "اتوریتی نامعتبر است.",
    -55: "تراکنش مورد نظر یافت نشد.",
    -60: "امکان ریورس کردن تراکنش با بانک وجود ندارد.",
    -61: "تراکنش موفق نیست یا قبلا ریورس شده است.",
    -62: "آی پی درگاه ست نشده است.",
    -63: "حداکثر زمان (۳۰ دقیقه) برای ریورس کردن این تراکنش منقضی شده است.",
    101: "تراکنش وریفای شده است.",
    400: "پرداخت از طرف درگاه تایید نشده است.",
    403: "تراکنش مورد نظر در دیتابیس وجود ندارد",
    404: "وریفای با موفقیت انجام نشده است",
    405: "خطایی هنگام اعتبار سنجی رخ داد، اطلاعات پرداخت به ادمین ها ارسال شد و نتیجه در ربات به شما اعلام خواهد شد.",
    "operation_failed_user": 'هنگام اجرای عملیات خطایی به وجود آمد! مبلغ {0} تومان به کیف پول شما اضافه شد. لطفا عملیات مورد نظر رو از طریق اعتبار کیف پول انجام بدید.',
    "successful_pay": 'پرداخت شما با موفقیت تایید شد!\n شماره تراکنش: {0}',
    "payment_failed_title": "پرداخت ناموفق",
    "payment_failed": "پرداخت شما ناموفق بود",
    "payment_failed_body": "متاسفانه پرداخت شما با خطا مواجه شد. دلیل خطا:",
    "error_code_lable": "کد خطا",
    "extra_text": "اگر فکر میکنید مشکلی وجود دارد، لطفا از طریق ربات با پشتیبانی در ارتباط باشید.",
    "back_to_bot": "بازگشت به ربات",
  }
}