"""a

Revision ID: 505ef73c8420
Revises: 9bf777dfa77e
Create Date: 2024-10-02 02:00:33.409186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '505ef73c8420'
down_revision: Union[str, None] = '9bf777dfa77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MainServer', 'server_protocol',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('Product', 'inbound_id')
    op.drop_column('Product', 'inbound_header_type')
    op.drop_column('Product', 'inbound_host')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('inbound_host', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Product', sa.Column('inbound_header_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Product', sa.Column('inbound_id', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.alter_column('MainServer', 'server_protocol',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
