"""a

Revision ID: 570e21338839
Revises: 
Create Date: 2024-10-03 02:23:15.318913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570e21338839'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Last_usage',
    sa.Column('last_usage_id', sa.Integer(), nullable=False),
    sa.Column('last_usage', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('last_usage_id')
    )
    op.create_table('MainServer',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('server_ip', sa.String(), nullable=True),
    sa.Column('server_protocol', sa.String(), nullable=True),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('server_username', sa.String(), nullable=True),
    sa.Column('server_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('Statistics',
    sa.Column('statistics_id', sa.Integer(), nullable=False),
    sa.Column('traffic_usage', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('statistics_id')
    )
    op.create_table('UserDetail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('free_service', sa.Boolean(), nullable=True),
    sa.Column('wallet', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['UserDetail.chat_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('FinancialReport',
    sa.Column('financial_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('id_holder', sa.Integer(), nullable=True),
    sa.Column('payment_getway', sa.String(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('url_callback', sa.String(), nullable=True),
    sa.Column('additional_data', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['UserDetail.chat_id'], ),
    sa.PrimaryKeyConstraint('financial_id')
    )
    op.create_table('Product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('main_server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_server_id'], ['MainServer.server_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('Purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('day_notification_stats', sa.Boolean(), nullable=True),
    sa.Column('traffic_notification_stats', sa.Boolean(), nullable=True),
    sa.Column('subscription_url', sa.String(), nullable=True),
    sa.Column('upgrade_traffic', sa.Integer(), nullable=True),
    sa.Column('upgrade_period', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['UserDetail.chat_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Purchase')
    op.drop_table('Product')
    op.drop_table('FinancialReport')
    op.drop_table('UserDetail')
    op.drop_table('Statistics')
    op.drop_table('MainServer')
    op.drop_table('Last_usage')
    # ### end Alembic commands ###
