"""a

Revision ID: 5f30b9c29d92
Revises: dd3229864aaf
Create Date: 2024-10-02 20:04:18.467860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f30b9c29d92'
down_revision: Union[str, None] = 'dd3229864aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FinancialReport', 'id_holder',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FinancialReport', 'id_holder',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
