"""a

Revision ID: 9ededa8f8296
Revises: 505ef73c8420
Create Date: 2024-10-02 18:29:12.351926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ededa8f8296'
down_revision: Union[str, None] = '505ef73c8420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Purchase', sa.Column('subscription_url', sa.String(), nullable=True))
    op.drop_column('Purchase', 'token')
    op.drop_column('Purchase', 'client_email')
    op.drop_column('Purchase', 'client_addresses')
    op.drop_column('Purchase', 'inbound_id')
    op.drop_column('Purchase', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Purchase', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Purchase', sa.Column('inbound_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Purchase', sa.Column('client_addresses', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Purchase', sa.Column('client_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Purchase', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Purchase', 'subscription_url')
    # ### end Alembic commands ###
