"""a

Revision ID: dd3229864aaf
Revises: 9ededa8f8296
Create Date: 2024-10-02 18:30:10.998363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3229864aaf'
down_revision: Union[str, None] = '9ededa8f8296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Purchase', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Purchase', 'username')
    # ### end Alembic commands ###
