"""Added new fields

Revision ID: f861f6768de6
Revises: 
Create Date: 2024-09-29 17:54:36.340080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f861f6768de6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inbound_id', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('sub_web_app_endpoint', sa.String(), nullable=True),
    sa.Column('inbound_host', sa.String(), nullable=True),
    sa.Column('inbound_header_type', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('Server',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('server_ip', sa.String(), nullable=True),
    sa.Column('server_protocol', sa.String(), nullable=True),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('server_user_name', sa.String(), nullable=True),
    sa.Column('server_password', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('country_name_short', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('connected_iran_server_ips', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('UserDetail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('free_service', sa.Boolean(), nullable=True),
    sa.Column('notification_gb', sa.Integer(), nullable=True),
    sa.Column('notification_day', sa.Integer(), nullable=True),
    sa.Column('wallet', sa.Integer(), nullable=True),
    sa.Column('notification_wallet', sa.Integer(), nullable=True),
    sa.Column('notif_wallet', sa.Integer(), nullable=True),
    sa.Column('notif_low_wallet', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('FinancialReport',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('financial_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('id_holder', sa.Integer(), nullable=True),
    sa.Column('payment_getway', sa.String(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('url_callback', sa.String(), nullable=True),
    sa.Column('additional_data', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['UserDetail.chat_id'], ),
    sa.PrimaryKeyConstraint('financial_id')
    )
    op.create_table('ProductServerAssociations',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['Server.server_id'], ),
    sa.PrimaryKeyConstraint('server_id', 'product_id')
    )
    op.create_table('Purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('inbound_id', sa.Integer(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('notif_day', sa.Boolean(), nullable=True),
    sa.Column('notif_gb', sa.Boolean(), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('vpn_server', sa.JSON(), nullable=True),
    sa.Column('client_addresses', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['UserDetail.chat_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('ClientServerAssociation',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('connected_iran_server_ips', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['Purchase.purchase_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['Server.server_id'], ),
    sa.PrimaryKeyConstraint('server_id', 'purchase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClientServerAssociation')
    op.drop_table('Purchase')
    op.drop_table('ProductServerAssociations')
    op.drop_table('FinancialReport')
    op.drop_table('UserDetail')
    op.drop_table('Server')
    op.drop_table('Product')
    # ### end Alembic commands ###
